CREATE TABLE BRAND(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL);

CREATE TABLE COUNTRY(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR (100) NOT NULL);

CREATE TABLE STRENGTH(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR (100) NOT NULL);

CREATE TABLE CIGAR(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR (100) NOT NULL,
brand_id INT NOT NULL,
country_id INT NOT NULL,
strength_id INT NOT NULL);
